

// Generates a map of track IDs to their order index in the results array
export const generateOrderMap = (results) => {
  return results.reduce((acc, track,index) => {
    acc[track.id] = index;  // Map each track ID to its index in the array
    return acc;             // Return the updated accumulator (order map) for the next iteration
  }, {});                   // Start with an empty object as the initial accumulator
};


// Reorders the results array based on the orderMap generated by generateOrderMap
export const reorderResults = (results, orderMap) => {
  return results.sort((a, b) => orderMap[a.id] - orderMap[b.id]); // Sort tracks according to their order in the orderMap
};